name: Build obs-plugin-axon.so (ARM64 RK3588)

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-arm64:
    name: Cross-compile obs-plugin-axon.so for ARM64
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install cross-compiler and tools
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt install libobs-dev libasound2-dev

      - name: Create build directory
        run: mkdir -p build-arm64

      - name: Configure (ARM64)
        run: |
          cd build-arm64
          cmake .. \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SHARED_LIBRARY_SUFFIX=.so

      - name: Build
        run: |
          cd build-arm64
          make -j$(nproc)

      - name: Rename output
        run: |
          cd build-arm64
          find . -name "*.so" -exec mv {} obs-plugin-axon.so \;

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-plugin-axon-arm64
          path: build-arm64/obs-plugin-axon.so

  release:
    if: github.event_name == 'release'
    name: Attach obs-plugin-axon.so to Release
    runs-on: ubuntu-24.04
    needs: build-arm64

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: obs-plugin-axon-arm64
          path: ./release_artifacts

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release_artifacts/obs-plugin-axon.so
